// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {app} from '../models';
import {service} from '../models';

export function CheckUpdate():Promise<updater.Asset>;

export function DeleteGame(arg1:string):Promise<void>;

export function DownloadAndLaunch(arg1:string):Promise<void>;

export function GetAllGameVersions():Promise<app.AllBranchVersions>;

export function GetAllNews():Promise<Array<service.NewsArticle>>;

export function GetBranchVersions(arg1:string):Promise<Array<number>>;

export function GetCrashReports():Promise<Array<service.CrashReport>>;

export function GetInstanceInfo():Promise<Record<string, any>>;

export function GetLatestNews():Promise<service.NewsArticle>;

export function GetLatestVersion(arg1:string):Promise<number>;

export function GetLauncherVersion():Promise<string>;

export function GetLocalGameVersion(arg1:string):Promise<string>;

export function GetLogs():Promise<string>;

export function GetNick():Promise<string>;

export function OpenFolder():Promise<void>;

export function SelectInstance(arg1:string):Promise<void>;

export function SetLocalGameVersion(arg1:string,arg2:string):Promise<void>;

export function SetNick(arg1:string,arg2:string):Promise<void>;

export function SyncInstanceState():Promise<void>;

export function Update():Promise<void>;

export function UpdateInstanceBranch(arg1:string):Promise<void>;

export function UpdateInstanceName(arg1:string):Promise<void>;

export function UpdateInstanceVersion(arg1:string):Promise<void>;

export function ValidateInstance():Promise<void>;
