// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function DeleteGame():Promise<void>;

export function DownloadAndLaunch(arg1:string):Promise<void>;

export function GetCrashReports():Promise<Array<app.CrashReport>>;

export function GetLogs():Promise<string>;

export function GetNick():Promise<string>;

export function GetVersions():Promise<string|string>;

export function OpenFolder():Promise<void>;

export function RunDiagnostics():Promise<app.DiagnosticReport>;

export function SaveDiagnosticReport():Promise<string>;

export function SetNick(arg1:string):Promise<void>;

export function Update():Promise<void>;
