// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {service} from '../models';

export function CheckUpdate():Promise<updater.Asset>;

export function DeleteGame(arg1:string):Promise<void>;

export function DownloadAndLaunch(arg1:string):Promise<void>;

export function GetCrashReports():Promise<Array<service.CrashReport>>;

export function GetLauncherVersion():Promise<string>;

export function GetLocalGameVersion(arg1:string):Promise<number>;

export function GetLogs():Promise<string>;

export function GetNick():Promise<string>;

export function OpenFolder():Promise<void>;

export function SetLocalGameVersion(arg1:number,arg2:string):Promise<void>;

export function SetNick(arg1:string,arg2:string):Promise<void>;

export function Update():Promise<void>;
