// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function DeleteGame() {
  return window['go']['app']['App']['DeleteGame']();
}

export function DownloadAndLaunch(arg1) {
  return window['go']['app']['App']['DownloadAndLaunch'](arg1);
}

export function GetCrashReports() {
  return window['go']['app']['App']['GetCrashReports']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetNick() {
  return window['go']['app']['App']['GetNick']();
}

export function GetVersions() {
  return window['go']['app']['App']['GetVersions']();
}

export function OpenFolder() {
  return window['go']['app']['App']['OpenFolder']();
}

export function RunDiagnostics() {
  return window['go']['app']['App']['RunDiagnostics']();
}

export function SaveDiagnosticReport() {
  return window['go']['app']['App']['SaveDiagnosticReport']();
}

export function SetNick(arg1) {
  return window['go']['app']['App']['SetNick'](arg1);
}

export function Update() {
  return window['go']['app']['App']['Update']();
}
