// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function DeleteGame(arg1) {
  return window['go']['app']['App']['DeleteGame'](arg1);
}

export function DownloadAndLaunch(arg1) {
  return window['go']['app']['App']['DownloadAndLaunch'](arg1);
}

export function GetCrashReports() {
  return window['go']['app']['App']['GetCrashReports']();
}

export function GetLauncherVersion() {
  return window['go']['app']['App']['GetLauncherVersion']();
}

export function GetLocalGameVersion(arg1) {
  return window['go']['app']['App']['GetLocalGameVersion'](arg1);
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetNick() {
  return window['go']['app']['App']['GetNick']();
}

export function OpenFolder() {
  return window['go']['app']['App']['OpenFolder']();
}

export function SetLocalGameVersion(arg1, arg2) {
  return window['go']['app']['App']['SetLocalGameVersion'](arg1, arg2);
}

export function SetNick(arg1, arg2) {
  return window['go']['app']['App']['SetNick'](arg1, arg2);
}

export function Update() {
  return window['go']['app']['App']['Update']();
}
